export const startMenuMessage = [
  ['COMANDO', 'AÇÃO'],
  [1, 'ENCONTRAR 5 ESTADOS COM MENOS CIDADES'],
  [2, 'ENCONTRAR 5 ESTADOS COM MAIS CIDADES'],
  [3, 'ENCONTRAR CIDADE COM MAIOR NOME DE CADA ESTADO'],
  [4, 'ENCONTRAR CIDADE COM MAIOR NOME'],
  [5, 'ENCONTRAR CIDADE COM MENOR NOME DE CADA ESTADO'],
  [6, 'ENCONTRAR CIDADE COM MENOR NOME'],
  [7, 'ENCONTRAR CIDADE DE UM ESTADO'],
  [8, 'CRIAR UM JSON PARA CADA ESTADO'],
  [0, 'SAIR']
];
